version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'mingnv'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    # Volumes này đang sử dụng theo dạng biến đó
    # Nó tương đương khai báo VOLUME trong Dockerfile, sinh volume dạng mã băm
    volumes:
      - db_data:/var/lib/mysql